# Generated by Django 4.2.7 on 2024-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_course_name_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
