# Generated by Django 4.2.7 on 2024-01-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_result_total_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-course']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-end_time']},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-name'], name='exam_course_name_50648b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-course'], name='exam_questi_course__aac138_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['-end_time'], name='exam_result_end_tim_3790c3_idx'),
        ),
    ]
