# Generated by Django 4.2.7 on 2024-01-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_level_alter_department_options_alter_user_options_and_more'),
        ('exam', '0017_course_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.level'),
        ),
    ]
