# Generated by Django 4.2.7 on 2024-01-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_name'),
        ('exam', '0018_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='users.department'),
        ),
    ]
