# Generated by Django 4.2.7 on 2024-01-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_remove_course_department_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
