# Generated by Django 4.2.7 on 2024-01-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_level'),
        ('exam', '0020_remove_course_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-question']},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='exam_questi_course__aac138_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(blank=True, to='users.department'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-question'], name='exam_questi_questio_4b40cb_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(blank=True, to='exam.course'),
        ),
    ]
