# Generated by Django 4.2.7 on 2024-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='D',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
