# Generated by Django 4.2.7 on 2024-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_question_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='control',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
