# Generated by Django 4.2.7 on 2024-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_alter_course_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_control',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
