# Generated by Django 4.2.7 on 2024-01-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_remove_course_view_result_viewresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_result', models.BooleanField(blank=True, default=False, null=True)),
                ('stop_time', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-view_result'],
            },
        ),
        migrations.DeleteModel(
            name='ViewResult',
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['-view_result'], name='exam_settin_view_re_44eda7_idx'),
        ),
    ]
