# Generated by Django 4.2.7 on 2024-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_alter_theory_question_student_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory_question',
            name='student_answer',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='theory_question',
            name='teacher_answer',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('semester', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['-name'], name='exam_school_name_b92420_idx')],
            },
        ),
    ]
