# Generated by Django 4.2.7 on 2024-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_theory_question_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='e_pin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
