# Generated by Django 4.2.7 on 2024-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
    ]
