# Generated by Django 4.2.7 on 2024-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
