# Generated by Django 4.2.7 on 2024-01-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-userid']},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['-name'], name='users_depar_name_4ef4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-userid'], name='users_user_userid_dc5d10_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['-name'], name='users_level_name_c6721c_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.level'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.level'),
        ),
    ]
