# Generated by Django 4.2.7 on 2024-01-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
