# Generated by Django 4.2.7 on 2024-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-department']},
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='users_depar_name_4ef4d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_userid_dc5d10_idx',
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['level'], name='users_depar_level_i_c6f612_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-department'], name='users_user_departm_b77304_idx'),
        ),
    ]
