# Generated by Django 4.2.7 on 2024-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_exammode_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammode',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
