# Generated by Django 4.2.7 on 2024-01-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_exammode_view_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammode',
            options={'ordering': ['-student']},
        ),
        migrations.AlterModelOptions(
            name='submitted',
            options={'ordering': ['-student']},
        ),
        migrations.AddIndex(
            model_name='exammode',
            index=models.Index(fields=['-student'], name='students_ex_student_3b209b_idx'),
        ),
        migrations.AddIndex(
            model_name='submitted',
            index=models.Index(fields=['-student'], name='students_su_student_85f05e_idx'),
        ),
    ]
