# Generated by Django 4.2.7 on 2024-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access_CountCount',
            new_name='Access_Count',
        ),
    ]
