# Generated by Django 4.2.7 on 2024-01-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_rename_access_countcount_access_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access_count',
            options={'ordering': ['-count']},
        ),
        migrations.AddIndex(
            model_name='access_count',
            index=models.Index(fields=['-count'], name='administrat_count_071858_idx'),
        ),
    ]
