# Generated by Django 4.2.7 on 2024-03-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_e_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_pin',
            options={'ordering': ['-used']},
        ),
        migrations.RemoveIndex(
            model_name='e_pin',
            name='administrat_used_733f4a_idx',
        ),
        migrations.AddIndex(
            model_name='e_pin',
            index=models.Index(fields=['-used'], name='administrat_used_cb8d29_idx'),
        ),
    ]
